package org.byconity.paimon.cli;

import com.google.common.collect.Lists;
import org.apache.paimon.CoreOptions;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class PaimonCliSsbTest extends PaimonCliTestBase {
    @Test
    public void testSsbNonPaimaryWithFormatOrc() throws Exception {
        testSsbNonPaimaryWithFormat(CoreOptions.FileFormatType.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/customer\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/date\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/part\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/supplier\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:6\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testSsbNonPaimaryWithFormatParquet() throws Exception {
        testSsbNonPaimaryWithFormat(CoreOptions.FileFormatType.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/customer\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/date\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/part\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/supplier\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:6\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testSsbNonPaimaryWithFormatAvro() throws Exception {
        testSsbNonPaimaryWithFormat(CoreOptions.FileFormatType.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/customer\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/date\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/part\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/supplier\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:6\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_non_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    private void testSsbNonPaimaryWithFormat(CoreOptions.FileFormatType format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "date", "lineorder", "part",
                "supplier", "lineorder_flat");
        String database = "test_ssb_non_paimary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/ssb/non-primary/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/ssb/%s.csv", table), 4096, '|');
        }
    }

    @Test
    public void testSsbPrimaryWithFormatOrc() throws Exception {
        testSsbPrimaryWithFormat(CoreOptions.FileFormatType.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_paimary' successfully.\n"
                        + "Create table 'test_ssb_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/customer\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.date' successfully.\n"
                        + "Table 'test_ssb_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\t\td_datekey\n" + "\tPartitionKeys:\n"
                        + "\tSchemaOptions:\n" + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/date\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.part' successfully.\n"
                        + "Table 'test_ssb_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/part\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/supplier\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:6\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_ssb_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testSsbPrimaryWithFormatParquet() throws Exception {
        testSsbPrimaryWithFormat(CoreOptions.FileFormatType.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_paimary' successfully.\n"
                        + "Create table 'test_ssb_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/customer\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.date' successfully.\n"
                        + "Table 'test_ssb_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\t\td_datekey\n" + "\tPartitionKeys:\n"
                        + "\tSchemaOptions:\n" + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/date\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.part' successfully.\n"
                        + "Table 'test_ssb_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/part\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/supplier\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:6\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_ssb_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testSsbPrimaryWithFormatAvro() throws Exception {
        testSsbPrimaryWithFormat(CoreOptions.FileFormatType.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_paimary' successfully.\n"
                        + "Create table 'test_ssb_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` INT NOT NULL\n" + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/customer\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.date' successfully.\n"
                        + "Table 'test_ssb_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t`d_datekey` INT NOT NULL\n" + "\t\t`d_date` VARCHAR(20) NOT NULL\n"
                        + "\t\t`d_dayofweek` VARCHAR(10) NOT NULL\n"
                        + "\t\t`d_month` VARCHAR(11) NOT NULL\n" + "\t\t`d_year` INT NOT NULL\n"
                        + "\t\t`d_yearmonthnum` INT NOT NULL\n"
                        + "\t\t`d_yearmonth` VARCHAR(9) NOT NULL\n"
                        + "\t\t`d_daynuminweek` INT NOT NULL\n"
                        + "\t\t`d_daynuminmonth` INT NOT NULL\n"
                        + "\t\t`d_daynuminyear` INT NOT NULL\n"
                        + "\t\t`d_monthnuminyear` INT NOT NULL\n"
                        + "\t\t`d_weeknuminyear` INT NOT NULL\n"
                        + "\t\t`d_sellingseason` VARCHAR(14) NOT NULL\n"
                        + "\t\t`d_lastdayinweekfl` INT NOT NULL\n"
                        + "\t\t`d_lastdayinmonthfl` INT NOT NULL\n"
                        + "\t\t`d_holidayfl` INT NOT NULL\n" + "\t\t`d_weekdayfl` INT NOT NULL\n"
                        + "\tPrimaryKeys:\n" + "\t\td_datekey\n" + "\tPartitionKeys:\n"
                        + "\tSchemaOptions:\n" + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/date\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.part' successfully.\n"
                        + "Table 'test_ssb_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` INT NOT NULL\n" + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/part\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` INT NOT NULL\n" + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/supplier\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t`lo_orderkey` INT NOT NULL\n" + "\t\t`lo_linenumber` INT NOT NULL\n"
                        + "\t\t`lo_custkey` INT NOT NULL\n" + "\t\t`lo_partkey` INT NOT NULL\n"
                        + "\t\t`lo_suppkey` INT NOT NULL\n" + "\t\t`lo_orderdate` DATE NOT NULL\n"
                        + "\t\t`lo_orderpriority` VARCHAR(16) NOT NULL\n"
                        + "\t\t`lo_shippriority` INT NOT NULL\n"
                        + "\t\t`lo_quantity` INT NOT NULL\n"
                        + "\t\t`lo_extendedprice` INT NOT NULL\n"
                        + "\t\t`lo_ordtotalprice` INT NOT NULL\n"
                        + "\t\t`lo_discount` INT NOT NULL\n" + "\t\t`lo_revenue` INT NOT NULL\n"
                        + "\t\t`lo_supplycost` INT NOT NULL\n" + "\t\t`lo_tax` INT NOT NULL\n"
                        + "\t\t`lo_commitdate` DATE NOT NULL\n"
                        + "\t\t`lo_shipmode` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(41) NOT NULL\n"
                        + "\t\t`c_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`c_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(26) NOT NULL\n"
                        + "\t\t`s_city` VARCHAR(11) NOT NULL\n"
                        + "\t\t`s_nation` VARCHAR(16) NOT NULL\n"
                        + "\t\t`s_region` VARCHAR(13) NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(16) NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(23) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(7) NOT NULL\n"
                        + "\t\t`p_category` VARCHAR(8) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_color` VARCHAR(12) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(26) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(11) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tlo_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:6\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_ssb_paimary.db/lineorder_flat\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_ssb_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n");
    }

    private void testSsbPrimaryWithFormat(CoreOptions.FileFormatType format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "date", "lineorder", "part",
                "supplier", "lineorder_flat");
        String database = "test_ssb_paimary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/ssb/primary/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/ssb/%s.csv", table), 4096, '|');
        }
    }
}
