package org.byconity.paimon.cli;

import com.google.common.collect.Lists;
import org.apache.paimon.CoreOptions;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class PaimonCliTpchTest extends PaimonCliTestBase {
    @Test
    public void testNonPrimaryTpchWithFormatOrc() throws Exception {
        testNonPrimaryTpchWithFormat(CoreOptions.FileFormatType.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/customer\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/lineitem\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/nation\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/orders\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/part\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/partsupp\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/region\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/supplier\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testNonPrimaryTpchWithFormatParquet() throws Exception {
        testNonPrimaryTpchWithFormat(CoreOptions.FileFormatType.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/customer\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/lineitem\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/nation\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/orders\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/part\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/partsupp\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/region\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/supplier\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testNonPrimaryTpchWithFormatAvro() throws Exception {
        testNonPrimaryTpchWithFormat(CoreOptions.FileFormatType.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/customer\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:3\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/lineitem\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/nation\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/orders\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/part\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/partsupp\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/region\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\tPartitionKeys:\n" + "\tSchemaOptions:\n" + "\t\tbucket:1\n"
                        + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_non_primary.db/supplier\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    private void testNonPrimaryTpchWithFormat(CoreOptions.FileFormatType format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "lineitem", "nation", "orders", "part",
                "partsupp", "region", "supplier");
        String database = "test_tpch_non_primary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/tpch/non-primary/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/tpch/%s.csv", table), 4096, ',');
        }
    }

    @Test
    public void testPrimaryTpchWithFormatOrc() throws Exception {
        testPrimaryTpchWithFormat(CoreOptions.FileFormatType.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_primary' successfully.\n"
                        + "Create table 'test_tpch_primary.customer' successfully.\n"
                        + "Table 'test_tpch_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/customer\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tl_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/lineitem\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.nation' successfully.\n"
                        + "Table 'test_tpch_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tn_nationkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/nation\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.orders' successfully.\n"
                        + "Table 'test_tpch_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\to_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/orders\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.part' successfully.\n"
                        + "Table 'test_tpch_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/part\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tps_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/partsupp\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.region' successfully.\n"
                        + "Table 'test_tpch_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tr_regionkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/region\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/supplier\n"
                        + "\t\tfile.format:orc\n"
                        + "Load table 'test_tpch_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testPrimaryTpchWithFormatParquet() throws Exception {
        testPrimaryTpchWithFormat(CoreOptions.FileFormatType.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_primary' successfully.\n"
                        + "Create table 'test_tpch_primary.customer' successfully.\n"
                        + "Table 'test_tpch_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/customer\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tl_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/lineitem\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.nation' successfully.\n"
                        + "Table 'test_tpch_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tn_nationkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/nation\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.orders' successfully.\n"
                        + "Table 'test_tpch_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\to_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/orders\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.part' successfully.\n"
                        + "Table 'test_tpch_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/part\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tps_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/partsupp\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.region' successfully.\n"
                        + "Table 'test_tpch_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tr_regionkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/region\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/supplier\n"
                        + "\t\tfile.format:parquet\n"
                        + "Load table 'test_tpch_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    @Test
    public void testPrimaryTpchWithFormatAvro() throws Exception {
        testPrimaryTpchWithFormat(CoreOptions.FileFormatType.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_primary' successfully.\n"
                        + "Create table 'test_tpch_primary.customer' successfully.\n"
                        + "Table 'test_tpch_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t`c_custkey` BIGINT NOT NULL\n"
                        + "\t\t`c_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`c_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`c_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`c_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`c_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`c_mktsegment` VARCHAR(10) NOT NULL\n"
                        + "\t\t`c_comment` VARCHAR(117) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tc_custkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/customer\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t`l_orderkey` BIGINT NOT NULL\n" + "\t\t`l_partkey` BIGINT NOT NULL\n"
                        + "\t\t`l_suppkey` BIGINT NOT NULL\n" + "\t\t`l_linenumber` INT NOT NULL\n"
                        + "\t\t`l_quantity` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_extendedprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_discount` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_tax` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`l_returnflag` CHAR(1) NOT NULL\n"
                        + "\t\t`l_linestatus` CHAR(1) NOT NULL\n"
                        + "\t\t`l_shipdate` DATE NOT NULL\n" + "\t\t`l_commitdate` DATE NOT NULL\n"
                        + "\t\t`l_receiptdate` DATE NOT NULL\n"
                        + "\t\t`l_shipinstruct` VARCHAR(25) NOT NULL\n"
                        + "\t\t`l_shipmode` VARCHAR(10) NOT NULL\n"
                        + "\t\t`l_comment` VARCHAR(44) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tl_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:3\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/lineitem\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.nation' successfully.\n"
                        + "Table 'test_tpch_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t`n_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`n_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`n_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`n_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tn_nationkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/nation\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.orders' successfully.\n"
                        + "Table 'test_tpch_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t`o_orderkey` BIGINT NOT NULL\n" + "\t\t`o_custkey` BIGINT NOT NULL\n"
                        + "\t\t`o_orderstatus` VARCHAR(1) NOT NULL\n"
                        + "\t\t`o_totalprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`o_orderdate` DATE NOT NULL\n"
                        + "\t\t`o_orderpriority` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_clerk` VARCHAR(15) NOT NULL\n"
                        + "\t\t`o_shippriority` INT NOT NULL\n"
                        + "\t\t`o_comment` VARCHAR(79) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\to_orderkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/orders\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.part' successfully.\n"
                        + "Table 'test_tpch_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t`p_partkey` BIGINT NOT NULL\n"
                        + "\t\t`p_name` VARCHAR(55) NOT NULL\n"
                        + "\t\t`p_mfgr` VARCHAR(25) NOT NULL\n"
                        + "\t\t`p_brand` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_type` VARCHAR(25) NOT NULL\n" + "\t\t`p_size` INT NOT NULL\n"
                        + "\t\t`p_container` VARCHAR(10) NOT NULL\n"
                        + "\t\t`p_retailprice` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`p_comment` VARCHAR(23) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tp_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/part\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t`ps_partkey` BIGINT NOT NULL\n"
                        + "\t\t`ps_suppkey` BIGINT NOT NULL\n" + "\t\t`ps_availqty` INT NOT NULL\n"
                        + "\t\t`ps_supplycost` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`ps_comment` VARCHAR(199) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tps_partkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/partsupp\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.region' successfully.\n"
                        + "Table 'test_tpch_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t`r_regionkey` BIGINT NOT NULL\n"
                        + "\t\t`r_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`r_comment` VARCHAR(152) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\tr_regionkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/region\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t`s_suppkey` BIGINT NOT NULL\n"
                        + "\t\t`s_name` VARCHAR(25) NOT NULL\n"
                        + "\t\t`s_address` VARCHAR(40) NOT NULL\n"
                        + "\t\t`s_nationkey` BIGINT NOT NULL\n"
                        + "\t\t`s_phone` VARCHAR(15) NOT NULL\n"
                        + "\t\t`s_acctbal` DECIMAL(15, 2) NOT NULL\n"
                        + "\t\t`s_comment` VARCHAR(101) NOT NULL\n" + "\tPrimaryKeys:\n"
                        + "\t\ts_suppkey\n" + "\tPartitionKeys:\n" + "\tSchemaOptions:\n"
                        + "\t\tbucket:1\n" + "\t\tfile.compression:zstd\n"
                        + "\t\tpath:/tmp/paimon_ut/test_tpch_primary.db/supplier\n"
                        + "\t\tfile.format:avro\n"
                        + "Load table 'test_tpch_primary.supplier' successfully, 16 rows have been inserted.\n");
    }

    private void testPrimaryTpchWithFormat(CoreOptions.FileFormatType format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "lineitem", "nation", "orders", "part",
                "partsupp", "region", "supplier");
        String database = "test_tpch_primary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/tpch/primary/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/tpch/%s.csv", table), 4096, ',');
        }
    }
}
