package org.byconity.iceberg.cli;

import com.google.common.collect.Lists;
import org.apache.iceberg.FileFormat;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class IcebergCliSsbTest extends IcebergCliTestBase {

    @Test
    public void testSsbNonPaimaryWithFormatOrc() throws Exception {
        testSsbNonPaimaryWithFormat(FileFormat.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required int\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n" + "\t\t4: c_city: required string\n"
                        + "\t\t5: c_nation: required string\n"
                        + "\t\t6: c_region: required string\n" + "\t\t7: c_phone: required string\n"
                        + "\t\t8: c_mktsegment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t1: d_datekey: required int\n" + "\t\t2: d_date: required string\n"
                        + "\t\t3: d_dayofweek: required string\n"
                        + "\t\t4: d_month: required string\n" + "\t\t5: d_year: required int\n"
                        + "\t\t6: d_yearmonthnum: required int\n"
                        + "\t\t7: d_yearmonth: required string\n"
                        + "\t\t8: d_daynuminweek: required int\n"
                        + "\t\t9: d_daynuminmonth: required int\n"
                        + "\t\t10: d_daynuminyear: required int\n"
                        + "\t\t11: d_monthnuminyear: required int\n"
                        + "\t\t12: d_weeknuminyear: required int\n"
                        + "\t\t13: d_sellingseason: required string\n"
                        + "\t\t14: d_lastdayinweekfl: required int\n"
                        + "\t\t15: d_lastdayinmonthfl: required int\n"
                        + "\t\t16: d_holidayfl: required int\n"
                        + "\t\t17: d_weekdayfl: required int\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required int\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n"
                        + "\t\t4: p_category: required string\n"
                        + "\t\t5: p_brand: required string\n" + "\t\t6: p_color: required string\n"
                        + "\t\t7: p_type: required string\n" + "\t\t8: p_size: required int\n"
                        + "\t\t9: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required int\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n" + "\t\t4: s_city: required string\n"
                        + "\t\t5: s_nation: required string\n"
                        + "\t\t6: s_region: required string\n" + "\t\t7: s_phone: required string\n"
                        + "\tPartitionFields:\n" + "\tSchemaProperties:\n"
                        + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n"
                        + "\t\t18: c_name: required string\n"
                        + "\t\t19: c_address: required string\n"
                        + "\t\t20: c_city: required string\n"
                        + "\t\t21: c_nation: required string\n"
                        + "\t\t22: c_region: required string\n"
                        + "\t\t23: c_phone: required string\n"
                        + "\t\t24: c_mktsegment: required string\n"
                        + "\t\t25: s_name: required string\n"
                        + "\t\t26: s_address: required string\n"
                        + "\t\t27: s_city: required string\n"
                        + "\t\t28: s_nation: required string\n"
                        + "\t\t29: s_region: required string\n"
                        + "\t\t30: s_phone: required string\n" + "\t\t31: p_name: required string\n"
                        + "\t\t32: p_mfgr: required string\n"
                        + "\t\t33: p_category: required string\n"
                        + "\t\t34: p_brand: required string\n"
                        + "\t\t35: p_color: required string\n" + "\t\t36: p_type: required string\n"
                        + "\t\t37: p_size: required int\n"
                        + "\t\t38: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    @Test
    public void testSsbNonPaimaryWithFormatParquet() throws Exception {
        testSsbNonPaimaryWithFormat(FileFormat.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required int\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n" + "\t\t4: c_city: required string\n"
                        + "\t\t5: c_nation: required string\n"
                        + "\t\t6: c_region: required string\n" + "\t\t7: c_phone: required string\n"
                        + "\t\t8: c_mktsegment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t1: d_datekey: required int\n" + "\t\t2: d_date: required string\n"
                        + "\t\t3: d_dayofweek: required string\n"
                        + "\t\t4: d_month: required string\n" + "\t\t5: d_year: required int\n"
                        + "\t\t6: d_yearmonthnum: required int\n"
                        + "\t\t7: d_yearmonth: required string\n"
                        + "\t\t8: d_daynuminweek: required int\n"
                        + "\t\t9: d_daynuminmonth: required int\n"
                        + "\t\t10: d_daynuminyear: required int\n"
                        + "\t\t11: d_monthnuminyear: required int\n"
                        + "\t\t12: d_weeknuminyear: required int\n"
                        + "\t\t13: d_sellingseason: required string\n"
                        + "\t\t14: d_lastdayinweekfl: required int\n"
                        + "\t\t15: d_lastdayinmonthfl: required int\n"
                        + "\t\t16: d_holidayfl: required int\n"
                        + "\t\t17: d_weekdayfl: required int\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required int\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n"
                        + "\t\t4: p_category: required string\n"
                        + "\t\t5: p_brand: required string\n" + "\t\t6: p_color: required string\n"
                        + "\t\t7: p_type: required string\n" + "\t\t8: p_size: required int\n"
                        + "\t\t9: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required int\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n" + "\t\t4: s_city: required string\n"
                        + "\t\t5: s_nation: required string\n"
                        + "\t\t6: s_region: required string\n" + "\t\t7: s_phone: required string\n"
                        + "\tPartitionFields:\n" + "\tSchemaProperties:\n"
                        + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n"
                        + "\t\t18: c_name: required string\n"
                        + "\t\t19: c_address: required string\n"
                        + "\t\t20: c_city: required string\n"
                        + "\t\t21: c_nation: required string\n"
                        + "\t\t22: c_region: required string\n"
                        + "\t\t23: c_phone: required string\n"
                        + "\t\t24: c_mktsegment: required string\n"
                        + "\t\t25: s_name: required string\n"
                        + "\t\t26: s_address: required string\n"
                        + "\t\t27: s_city: required string\n"
                        + "\t\t28: s_nation: required string\n"
                        + "\t\t29: s_region: required string\n"
                        + "\t\t30: s_phone: required string\n" + "\t\t31: p_name: required string\n"
                        + "\t\t32: p_mfgr: required string\n"
                        + "\t\t33: p_category: required string\n"
                        + "\t\t34: p_brand: required string\n"
                        + "\t\t35: p_color: required string\n" + "\t\t36: p_type: required string\n"
                        + "\t\t37: p_size: required int\n"
                        + "\t\t38: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    @Test
    public void testSsbNonPaimaryWithFormatAvro() throws Exception {
        testSsbNonPaimaryWithFormat(FileFormat.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_ssb_non_paimary' successfully.\n"
                        + "Create table 'test_ssb_non_paimary.customer' successfully.\n"
                        + "Table 'test_ssb_non_paimary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required int\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n" + "\t\t4: c_city: required string\n"
                        + "\t\t5: c_nation: required string\n"
                        + "\t\t6: c_region: required string\n" + "\t\t7: c_phone: required string\n"
                        + "\t\t8: c_mktsegment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.date' successfully.\n"
                        + "Table 'test_ssb_non_paimary.date' schema:\n" + "\tFields:\n"
                        + "\t\t1: d_datekey: required int\n" + "\t\t2: d_date: required string\n"
                        + "\t\t3: d_dayofweek: required string\n"
                        + "\t\t4: d_month: required string\n" + "\t\t5: d_year: required int\n"
                        + "\t\t6: d_yearmonthnum: required int\n"
                        + "\t\t7: d_yearmonth: required string\n"
                        + "\t\t8: d_daynuminweek: required int\n"
                        + "\t\t9: d_daynuminmonth: required int\n"
                        + "\t\t10: d_daynuminyear: required int\n"
                        + "\t\t11: d_monthnuminyear: required int\n"
                        + "\t\t12: d_weeknuminyear: required int\n"
                        + "\t\t13: d_sellingseason: required string\n"
                        + "\t\t14: d_lastdayinweekfl: required int\n"
                        + "\t\t15: d_lastdayinmonthfl: required int\n"
                        + "\t\t16: d_holidayfl: required int\n"
                        + "\t\t17: d_weekdayfl: required int\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.date' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.part' successfully.\n"
                        + "Table 'test_ssb_non_paimary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required int\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n"
                        + "\t\t4: p_category: required string\n"
                        + "\t\t5: p_brand: required string\n" + "\t\t6: p_color: required string\n"
                        + "\t\t7: p_type: required string\n" + "\t\t8: p_size: required int\n"
                        + "\t\t9: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.supplier' successfully.\n"
                        + "Table 'test_ssb_non_paimary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required int\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n" + "\t\t4: s_city: required string\n"
                        + "\t\t5: s_nation: required string\n"
                        + "\t\t6: s_region: required string\n" + "\t\t7: s_phone: required string\n"
                        + "\tPartitionFields:\n" + "\tSchemaProperties:\n"
                        + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.supplier' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_ssb_non_paimary.lineorder_flat' successfully.\n"
                        + "Table 'test_ssb_non_paimary.lineorder_flat' schema:\n" + "\tFields:\n"
                        + "\t\t1: lo_orderkey: required int\n"
                        + "\t\t2: lo_linenumber: required int\n"
                        + "\t\t3: lo_custkey: required int\n" + "\t\t4: lo_partkey: required int\n"
                        + "\t\t5: lo_suppkey: required int\n"
                        + "\t\t6: lo_orderdate: required date\n"
                        + "\t\t7: lo_orderpriority: required string\n"
                        + "\t\t8: lo_shippriority: required int\n"
                        + "\t\t9: lo_quantity: required int\n"
                        + "\t\t10: lo_extendedprice: required int\n"
                        + "\t\t11: lo_ordtotalprice: required int\n"
                        + "\t\t12: lo_discount: required int\n"
                        + "\t\t13: lo_revenue: required int\n"
                        + "\t\t14: lo_supplycost: required int\n" + "\t\t15: lo_tax: required int\n"
                        + "\t\t16: lo_commitdate: required date\n"
                        + "\t\t17: lo_shipmode: required string\n"
                        + "\t\t18: c_name: required string\n"
                        + "\t\t19: c_address: required string\n"
                        + "\t\t20: c_city: required string\n"
                        + "\t\t21: c_nation: required string\n"
                        + "\t\t22: c_region: required string\n"
                        + "\t\t23: c_phone: required string\n"
                        + "\t\t24: c_mktsegment: required string\n"
                        + "\t\t25: s_name: required string\n"
                        + "\t\t26: s_address: required string\n"
                        + "\t\t27: s_city: required string\n"
                        + "\t\t28: s_nation: required string\n"
                        + "\t\t29: s_region: required string\n"
                        + "\t\t30: s_phone: required string\n" + "\t\t31: p_name: required string\n"
                        + "\t\t32: p_mfgr: required string\n"
                        + "\t\t33: p_category: required string\n"
                        + "\t\t34: p_brand: required string\n"
                        + "\t\t35: p_color: required string\n" + "\t\t36: p_type: required string\n"
                        + "\t\t37: p_size: required int\n"
                        + "\t\t38: p_container: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_ssb_non_paimary.lineorder_flat' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    private void testSsbNonPaimaryWithFormat(FileFormat format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "date", "lineorder", "part",
                "supplier", "lineorder_flat");
        String database = "test_ssb_non_paimary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/ssb/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/ssb/%s.csv", table), 4096, '|');
        }
    }
}
