package org.byconity.iceberg.cli;

import com.google.common.collect.Lists;
import org.apache.iceberg.FileFormat;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class IcebergCliTpchTest extends IcebergCliTestBase {
    @Test
    public void testNonPrimaryTpchWithFormatOrc() throws Exception {
        testNonPrimaryTpchWithFormat(FileFormat.ORC);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required long\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n"
                        + "\t\t4: c_nationkey: required long\n"
                        + "\t\t5: c_phone: required string\n"
                        + "\t\t6: c_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: c_mktsegment: required string\n"
                        + "\t\t8: c_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t1: l_orderkey: required long\n" + "\t\t2: l_partkey: required long\n"
                        + "\t\t3: l_suppkey: required long\n"
                        + "\t\t4: l_linenumber: required int\n"
                        + "\t\t5: l_quantity: required decimal(15, 2)\n"
                        + "\t\t6: l_extendedprice: required decimal(15, 2)\n"
                        + "\t\t7: l_discount: required decimal(15, 2)\n"
                        + "\t\t8: l_tax: required decimal(15, 2)\n"
                        + "\t\t9: l_returnflag: required string\n"
                        + "\t\t10: l_linestatus: required string\n"
                        + "\t\t11: l_shipdate: required date\n"
                        + "\t\t12: l_commitdate: required date\n"
                        + "\t\t13: l_receiptdate: required date\n"
                        + "\t\t14: l_shipinstruct: required string\n"
                        + "\t\t15: l_shipmode: required string\n"
                        + "\t\t16: l_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t1: n_nationkey: required long\n" + "\t\t2: n_name: required string\n"
                        + "\t\t3: n_regionkey: required long\n"
                        + "\t\t4: n_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t1: o_orderkey: required long\n" + "\t\t2: o_custkey: required long\n"
                        + "\t\t3: o_orderstatus: required string\n"
                        + "\t\t4: o_totalprice: required decimal(15, 2)\n"
                        + "\t\t5: o_orderdate: required date\n"
                        + "\t\t6: o_orderpriority: required string\n"
                        + "\t\t7: o_clerk: required string\n"
                        + "\t\t8: o_shippriority: required int\n"
                        + "\t\t9: o_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required long\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n" + "\t\t4: p_brand: required string\n"
                        + "\t\t5: p_type: required string\n" + "\t\t6: p_size: required int\n"
                        + "\t\t7: p_container: required string\n"
                        + "\t\t8: p_retailprice: required decimal(15, 2)\n"
                        + "\t\t9: p_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t1: ps_partkey: required long\n"
                        + "\t\t2: ps_suppkey: required long\n"
                        + "\t\t3: ps_availqty: required int\n"
                        + "\t\t4: ps_supplycost: required decimal(15, 2)\n"
                        + "\t\t5: ps_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t1: r_regionkey: required long\n" + "\t\t2: r_name: required string\n"
                        + "\t\t3: r_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required long\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n"
                        + "\t\t4: s_nationkey: required long\n"
                        + "\t\t5: s_phone: required string\n"
                        + "\t\t6: s_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: s_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:ORC\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    @Test
    public void testNonPrimaryTpchWithFormatParquet() throws Exception {
        testNonPrimaryTpchWithFormat(FileFormat.PARQUET);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required long\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n"
                        + "\t\t4: c_nationkey: required long\n"
                        + "\t\t5: c_phone: required string\n"
                        + "\t\t6: c_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: c_mktsegment: required string\n"
                        + "\t\t8: c_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t1: l_orderkey: required long\n" + "\t\t2: l_partkey: required long\n"
                        + "\t\t3: l_suppkey: required long\n"
                        + "\t\t4: l_linenumber: required int\n"
                        + "\t\t5: l_quantity: required decimal(15, 2)\n"
                        + "\t\t6: l_extendedprice: required decimal(15, 2)\n"
                        + "\t\t7: l_discount: required decimal(15, 2)\n"
                        + "\t\t8: l_tax: required decimal(15, 2)\n"
                        + "\t\t9: l_returnflag: required string\n"
                        + "\t\t10: l_linestatus: required string\n"
                        + "\t\t11: l_shipdate: required date\n"
                        + "\t\t12: l_commitdate: required date\n"
                        + "\t\t13: l_receiptdate: required date\n"
                        + "\t\t14: l_shipinstruct: required string\n"
                        + "\t\t15: l_shipmode: required string\n"
                        + "\t\t16: l_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t1: n_nationkey: required long\n" + "\t\t2: n_name: required string\n"
                        + "\t\t3: n_regionkey: required long\n"
                        + "\t\t4: n_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t1: o_orderkey: required long\n" + "\t\t2: o_custkey: required long\n"
                        + "\t\t3: o_orderstatus: required string\n"
                        + "\t\t4: o_totalprice: required decimal(15, 2)\n"
                        + "\t\t5: o_orderdate: required date\n"
                        + "\t\t6: o_orderpriority: required string\n"
                        + "\t\t7: o_clerk: required string\n"
                        + "\t\t8: o_shippriority: required int\n"
                        + "\t\t9: o_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required long\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n" + "\t\t4: p_brand: required string\n"
                        + "\t\t5: p_type: required string\n" + "\t\t6: p_size: required int\n"
                        + "\t\t7: p_container: required string\n"
                        + "\t\t8: p_retailprice: required decimal(15, 2)\n"
                        + "\t\t9: p_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t1: ps_partkey: required long\n"
                        + "\t\t2: ps_suppkey: required long\n"
                        + "\t\t3: ps_availqty: required int\n"
                        + "\t\t4: ps_supplycost: required decimal(15, 2)\n"
                        + "\t\t5: ps_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t1: r_regionkey: required long\n" + "\t\t2: r_name: required string\n"
                        + "\t\t3: r_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required long\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n"
                        + "\t\t4: s_nationkey: required long\n"
                        + "\t\t5: s_phone: required string\n"
                        + "\t\t6: s_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: s_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:PARQUET\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    @Test
    public void testNonPrimaryTpchWithFormatAvro() throws Exception {
        testNonPrimaryTpchWithFormat(FileFormat.AVRO);
        Assert.assertEquals(testOut.getContent(),
                "Create database 'test_tpch_non_primary' successfully.\n"
                        + "Create table 'test_tpch_non_primary.customer' successfully.\n"
                        + "Table 'test_tpch_non_primary.customer' schema:\n" + "\tFields:\n"
                        + "\t\t1: c_custkey: required long\n" + "\t\t2: c_name: required string\n"
                        + "\t\t3: c_address: required string\n"
                        + "\t\t4: c_nationkey: required long\n"
                        + "\t\t5: c_phone: required string\n"
                        + "\t\t6: c_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: c_mktsegment: required string\n"
                        + "\t\t8: c_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.customer' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.lineitem' successfully.\n"
                        + "Table 'test_tpch_non_primary.lineitem' schema:\n" + "\tFields:\n"
                        + "\t\t1: l_orderkey: required long\n" + "\t\t2: l_partkey: required long\n"
                        + "\t\t3: l_suppkey: required long\n"
                        + "\t\t4: l_linenumber: required int\n"
                        + "\t\t5: l_quantity: required decimal(15, 2)\n"
                        + "\t\t6: l_extendedprice: required decimal(15, 2)\n"
                        + "\t\t7: l_discount: required decimal(15, 2)\n"
                        + "\t\t8: l_tax: required decimal(15, 2)\n"
                        + "\t\t9: l_returnflag: required string\n"
                        + "\t\t10: l_linestatus: required string\n"
                        + "\t\t11: l_shipdate: required date\n"
                        + "\t\t12: l_commitdate: required date\n"
                        + "\t\t13: l_receiptdate: required date\n"
                        + "\t\t14: l_shipinstruct: required string\n"
                        + "\t\t15: l_shipmode: required string\n"
                        + "\t\t16: l_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.lineitem' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.nation' successfully.\n"
                        + "Table 'test_tpch_non_primary.nation' schema:\n" + "\tFields:\n"
                        + "\t\t1: n_nationkey: required long\n" + "\t\t2: n_name: required string\n"
                        + "\t\t3: n_regionkey: required long\n"
                        + "\t\t4: n_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.nation' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.orders' successfully.\n"
                        + "Table 'test_tpch_non_primary.orders' schema:\n" + "\tFields:\n"
                        + "\t\t1: o_orderkey: required long\n" + "\t\t2: o_custkey: required long\n"
                        + "\t\t3: o_orderstatus: required string\n"
                        + "\t\t4: o_totalprice: required decimal(15, 2)\n"
                        + "\t\t5: o_orderdate: required date\n"
                        + "\t\t6: o_orderpriority: required string\n"
                        + "\t\t7: o_clerk: required string\n"
                        + "\t\t8: o_shippriority: required int\n"
                        + "\t\t9: o_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.orders' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.part' successfully.\n"
                        + "Table 'test_tpch_non_primary.part' schema:\n" + "\tFields:\n"
                        + "\t\t1: p_partkey: required long\n" + "\t\t2: p_name: required string\n"
                        + "\t\t3: p_mfgr: required string\n" + "\t\t4: p_brand: required string\n"
                        + "\t\t5: p_type: required string\n" + "\t\t6: p_size: required int\n"
                        + "\t\t7: p_container: required string\n"
                        + "\t\t8: p_retailprice: required decimal(15, 2)\n"
                        + "\t\t9: p_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.part' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.partsupp' successfully.\n"
                        + "Table 'test_tpch_non_primary.partsupp' schema:\n" + "\tFields:\n"
                        + "\t\t1: ps_partkey: required long\n"
                        + "\t\t2: ps_suppkey: required long\n"
                        + "\t\t3: ps_availqty: required int\n"
                        + "\t\t4: ps_supplycost: required decimal(15, 2)\n"
                        + "\t\t5: ps_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.partsupp' successfully, 16 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.region' successfully.\n"
                        + "Table 'test_tpch_non_primary.region' schema:\n" + "\tFields:\n"
                        + "\t\t1: r_regionkey: required long\n" + "\t\t2: r_name: required string\n"
                        + "\t\t3: r_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.region' successfully, 5 rows have been inserted.\n"
                        + "Create table 'test_tpch_non_primary.supplier' successfully.\n"
                        + "Table 'test_tpch_non_primary.supplier' schema:\n" + "\tFields:\n"
                        + "\t\t1: s_suppkey: required long\n" + "\t\t2: s_name: required string\n"
                        + "\t\t3: s_address: required string\n"
                        + "\t\t4: s_nationkey: required long\n"
                        + "\t\t5: s_phone: required string\n"
                        + "\t\t6: s_acctbal: required decimal(15, 2)\n"
                        + "\t\t7: s_comment: required string\n" + "\tPartitionFields:\n"
                        + "\tSchemaProperties:\n" + "\t\twrite.format.default:AVRO\n"
                        + "\t\twrite.parquet.compression-codec:zstd\n"
                        + "Load table 'test_tpch_non_primary.supplier' successfully, 16 rows have been inserted.\n",
                testOut.getContent());
    }

    private void testNonPrimaryTpchWithFormat(FileFormat format) throws Exception {
        List<String> tables = Lists.newArrayList("customer", "lineitem", "nation", "orders", "part",
                "partsupp", "region", "supplier");
        String database = "test_tpch_non_primary";
        createDatabase(database);
        for (String table : tables) {
            createTableWithFormat(database, table, format,
                    String.format("/tpch/%s_template.json", table));
            showTableSchema(database, table);
            loadTable(database, table, String.format("/tpch/%s.csv", table), 4096, ',');
        }
    }
}
